My home work 9(modules and pip)
yaroslavyvk/homework-prj pull request #2
Opened 2023-08-27 07:53 UTC by yaroslavyvk

2023-08-27 12:11 UTC, bielanm requested changes

2023-08-27 12:11 UTC, bielanm commented on hw9/requirements.txt
> +numpy==1.25.2
Зазвичай нам треба щоб в `requirements.txt` були лише ті залежності, від яких залежить проєкт. В нашому випадку це ли numpy.
Command:  `pip freeze | grep numpy > requirements.txt`

2023-08-27 12:11 UTC, bielanm commented on hw9/Modules/__pycache__/hello.cpython-310.pyc
Створи в репозиторії файл `.gitignore` і додай тут рядок `__pycache__/`.
Бо ці файли відносяться до твого програмного оточення, а не до проєкту (ще й займають дуже багато місця).

Можеш скопіювати вміст https://github.com/github/gitignore/blob/main/Python.gitignore собі в .gitignore - там зібрані найчастіші паттерни, яких треба уникати в репозиторії.

2023-08-27 12:11 UTC, bielanm commented on hw9/Modules/__pycache__/hello.cpython-310.pyc
Ну і не забудь видалити `__pycache__` з репозиторія.

2023-08-27 12:46 UTC, yaroslavyvk commented on hw9/Modules/__pycache__/hello.cpython-310.pyc
Тобто все що не мій файл з кодом краще не грузити в репозиторій, тому що це програмне оточення? 

.gitignore  також комітити і відправляти на ремоут чи його можна якось локально зберігати?

2023-08-27 17:05 UTC, bielanm commented on hw9/Modules/__pycache__/hello.cpython-310.pyc
> Тобто все що не мій файл з кодом краще не грузити в репозиторій, тому що це програмне оточення?
так
> .gitignore також комітити і відправляти на ремоут чи його можна якось локально зберігати?
так

2023-08-28 18:46 UTC, yaroslavyvk commented
Зробив поправки. Добавив в requirements.txt тільки numpy. і видалив __py__

2023-08-31 21:03 UTC, bielanm approved these changes

2023-09-01 07:40 UTC, merged