Add my hw16, sql file
yaroslavyvk/homework-prj pull request #8
Opened 2023-09-20 09:19 UTC by yaroslavyvk

2023-09-21 21:00 UTC, bielanm requested changes

2023-09-21 21:00 UTC, bielanm commented on hw16/hw16.session.sql
> +    AND DATE_TRUNC('month', current_date) - INTERVAL '1 month' <= Reservations.start_date
а чому не `current_date  - INTERVAL '1 month'`?

2023-09-22 18:01 UTC, yaroslavyvk commented on hw16/hw16.session.sql
> +    AND DATE_TRUNC('month', current_date) - INTERVAL '1 month' <= Reservations.start_date
ну я подумав що нам потрібно вивести інформацію тільки за попередній місяць. Тому обнулив цей місяць до 1 числа і відняв один місяць . Тим самим, воно по ідеї має порахувати всі резерви які були зроблені за серпень до цієї дати.

2023-09-22 18:15 UTC, yaroslavyvk commented on hw16/hw16.session.sql
> +    amount FLOAT NOT NULL,
так, маєш рацію. Копійки не можна втрачати. Перероблю зараз.

2023-09-26 22:01 UTC, bielanm commented on hw16/hw16.session.sql
> +    AND DATE_TRUNC('month', current_date) - INTERVAL '1 month' <= Reservations.start_date
ok

2023-09-26 22:01 UTC, bielanm approved these changes

2023-09-27 07:04 UTC, merged